name: Terraform Build & Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '/terraform'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TF_VAR_TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
      TF_VAR_TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      TF_VAR_TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TF_VAR_TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      TF_VAR_AZURE_ACCESS_KEY: ${{ secrets.AZURE_ACCESS_KEY }}
      TF_VAR_AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
      TF_VAR_AZURE_CONTAINER_NAME: ${{ secrets.AZURE_CONTAINER_NAME }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: '{"clientId":"${{ secrets.AZURE_APPID }}","clientSecret":"${{ secrets.AZURE_PASSWORD }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION }}","tenantId":"${{ secrets.AZURE_TENANT }}"}'
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      with:
        terraform_wrapper: false
    - name: Terraform Init
      run: terraform init -backend-config="access_key=$TF_VAR_AZURE_ACCESS_KEY" -backend-config="storage_account_name=$TF_VAR_AZURE_STORAGE_ACCOUNT_NAME" -backend-config="container_name=$TF_VAR_AZURE_CONTAINER_NAME" -backend-config="key=terraform.tfstate"
      working-directory: ./terraform
    - name: Terraform Plan
      run: terraform plan
      working-directory: ./terraform
    - name: Terraform Apply
      run: terraform apply -no-color -input=false -auto-approve
      working-directory: ./terraform
