name: Publish AZ FunctionApp after Terraform Deployment
on:
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: '{"clientId":"${{ secrets.AZURE_APPID }}","clientSecret":"${{ secrets.AZURE_PASSWORD }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION }}","tenantId":"${{ secrets.AZURE_TENANT }}"}'
    - name: Install Azure functions core tools onto runner
      run: |
         sudo apt-get install azure-functions-core-tools

    - name: Set up Python 3.11.7
      if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.7"

    - uses: actions/cache@v3
      id: cache
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{hashFiles('requirements.txt') }}
        
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements.txt --target="AzureDeploymentTweeterLinux/requirements.txt"
      working-directory: ./AzureDeploymentTweeterLinux
    
    - name: Install venv
      run: |
        python -m venv .venv
        source .venv/bin/activate
      working-directory: ./AzureDeploymentTweeterLinux
      
    - name: publish
      run: |
        func azure functionapp publish usnytpythontwitterbotter --slot dev --python
      working-directory: ./AzureDeploymentTweeterLinux
